### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by marksev1** [praxeo/mycroft_spaceflightnow_skill#1]
2017-01-07 12:10:26,282 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): spaceflightnow.com
2017-01-07 12:10:26,995 - requests.packages.urllib3.connectionpool - DEBUG - "GET /launch-schedule/ HTTP/1.1" 200 15252
2017-01-07 12:10:27,127 - SkillContainer - DEBUG - {"data": {"utterance": "An error occurred while processing a request in NextLaunchSkill"}, "type": "speak", "context": null}
2017-01-07 12:10:27,128 - SkillContainer - DEBUG - {"data": {}, "type": "recognizer_loop:audio_output_start", "context": null}
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
'NoneType' object has no attribute 'group'
[]
2017-01-07 12:10:27,284 - mycroft.skills.core - ERROR - An error occurred while processing a request in NextLaunchSkill
Traceback (most recent call last):
  File "/home/msev/mycroft-core/mycroft/skills/core.py", line 200, in receive_handler
    handler(message)
  File "/home/msev/mycroft-core/mycroft/skills/mycroft_spaceflightnow_skill/__init__.py", line 71, in handle_next_launch_intent
    self.speak_dialog("next.launch", sorted_schedule[0])
IndexError: list index out of range

I'm using the latest mycroft from master.

**Comment by JarbasAI** [comment]
its a problem with re , it was working before, im new to python and dont know the syntax to fix it, but commenting those 2 lines or making slight changes lets the script run

**Comment by marksev1** [comment]
I have made my own version of space launch skill so gonna  put in on github shortly.

**Comment by awesomebjt** [comment]
Thanks for bringing this up, and sorry for not noticing this sooner. I'll work out a fix.
